### ISSUE TITLE
Create CSS Grid Columns - 2 columns (30% / 70%) using "fr" unit

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#100]
We need a class to define those column sizes
Please write your code in this file: https://github.com/maevanapcontact/Ulight/blob/master/src/scss/styles.scss

Plase create a second class to achieve the same result but with a gap (between columns only) of 1em

**Comment by valnicky** [comment]
Hi, I'll try to do this one, :)

**Comment by valnicky** [comment]
I'll ask you because I have doubt and I don't want to make a mistake
Do I have to add to style.scss this :
//GRID 2 COLUMNS
  .col-3-7{
    display: grid;
    grid-template-columns: 3fr 7fr;
  }

  .col-3-7-gap-1em{
    display: grid;
    grid-template-columns: 3fr 7fr;
    grid-column-gap: 1em;
  }
thank you

**Comment by maevanapcontact** [comment]
yeah that's it :) 
(Sorry for the delay)
