### ISSUE TITLE
Create CSS Grid columns - 3 columns (20% / 60% / 20%) using "fr" unit

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#101]
We need a class to define those column sizes
Please write your code in this file: https://github.com/maevanapcontact/Ulight/blob/master/src/scss/styles.scss

Plase create a second class to achieve the same result but with a gap (between columns only) of 1em

**Comment by Islam888** [comment]
This one is with me too

**Comment by Islam888** [comment]
// classes for grids of 3 columns 20%-60%-20%

.col-1-3-1{
    display: grid;
    grid-template-columns: 1fr 3fr 1fr;
}

.col-1-3-1-gap{
    display: grid;
    grid-template-columns: 1fr 3fr 1fr;
    grid-column-gap: 1em;
}

**Comment by maevanapcontact** [comment]
OK for me!
