### ISSUE TITLE
Create CSS Grid columns - 2 columns (70% / 30%) using "fr" units

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#102]
We need a class to define those column sizes
Please write your code in this file: https://github.com/maevanapcontact/Ulight/blob/master/src/scss/styles.scss

Plase create a second class to achieve the same result but with a gap (between columns only) of 1em

**Comment by Islam888** [comment]
I am taking this one.

**Comment by Islam888** [comment]
//classes for grids of 2 columns 70%-30%
.col-7-3{
    display: grid;
    grid-template-columns: 7fr 3fr;
}

.col-7-3-gap{
    display: grid;
    grid-template-columns: 7fr 3fr;
    grid-column-gap: 1em;
}

**Comment by maevanapcontact** [comment]
OK for me!
