### ISSUE TITLE
Create CSS Grid columns - 4 columns (10% / 40% / 40% / 10%) using "fr" unit

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#103]
We need a class to define those column sizes
Please write your code in this file: https://github.com/maevanapcontact/Ulight/blob/master/src/scss/styles.scss

Plase create a second class to achieve the same result but with a gap (between columns only) of 1em

**Comment by Islam888** [comment]
Hi!
I am taking this issue.

**Comment by Islam888** [comment]
//classes for grids of 4 columns 10%-40%-40%-10%
.col-1-4-4-1{
    display: grid;
    grid-template-columns: 1fr repeat(2, 4fr) 1fr;
}

.col-1-4-4-1-gap{
    display: grid;
    grid-template-columns: 1fr repeat(2, 4fr) 1fr;
    grid-column-gap: 1em;
}

**Comment by maevanapcontact** [comment]
OK for me!

**Comment by Islam888** [comment]
.col-10-40-40-10{
    display: grid;
    grid-template-columns: 1fr repeat(2, 4fr) 1fr;
    grid-template-areas: "col1 col2 col3 col4";
}

.col-10-40-40-10-gap{
    display: grid;
    grid-template-columns: 1fr repeat(2, 4fr) 1fr;
    grid-template-areas: "col1 col2 col3 col4";
    grid-column-gap: 1em;
}

.col1{
    grid-area: col1;
    background: rgb(87, 10, 25);
}
.col2{
    grid-area: col2;
    background: rgb(87, 10, 75);
}
.col3{
    grid-area: col3;
    background: rgb(87, 10, 125);
}
.col4{
    grid-area: col4;
    background: rgb(87, 10, 200);
}
