### ISSUE TITLE
Create CSS Grid columns - 3 columns (20% / 40% / 40%) using "fr" unit

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#104]
We need a class to define those column sizes
Please write your code in this file: https://github.com/maevanapcontact/Ulight/blob/master/src/scss/styles.scss

Plase create a second class to achieve the same result but with a gap (between columns only) of 1em

**Comment by inass-helmy** [comment]
I’ll take this one

**Comment by inass-helmy** [comment]
Here is the code should I pull a request?

.col-1fr-2fr-2fr{
display: grid;
grid-template-columns: 1fr 2fr 2fr;
}

.col-1fr-2fr-2fr-gap-1em {
display: grid;
grid-template-columns: 1fr 2fr 2fr;
grid-column-gap: 1em;
}

**Comment by maevanapcontact** [comment]
OK for me!
Could you please, use those classes names:

.col-1-2-2

and 

.col-1-2-2-gap

?

**Comment by inass-helmy** [comment]
ok
