### ISSUE TITLE
Create CSS Grid columns - 3 columns (40% / 40% / 20%) using "fr" units

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#105]
We need a class to define those column sizes
Please write your code in this file: https://github.com/maevanapcontact/Ulight/blob/master/src/scss/styles.scss

Plase create a second class to achieve the same result but with a gap (between columns only) of 1em

**Comment by yigitserdar** [comment]
I'm on it

**Comment by yigitserdar** [comment]
what do you think about this?

`// classes of 3 columns (40% / 40% / 20%) using "fr" units

.col-4-4-2 {
  display: grid;
  grid-template-columns: 2fr 2fr 1fr;
}

.col-4-4-2-gap-1em {
    display: grid;
    grid-template-columns: 2fr 2fr 1fr;
    grid-column-gap: 1em;
}`

**Comment by maevanapcontact** [comment]
It looks great :)
Maybe it should be good to rename the classes accordingly to the "fr" units?

**Comment by yigitserdar** [comment]
ok like: .col-4fr-4fr-2fr ?

**Comment by maevanapcontact** [comment]
could it be .col-4-4-2 and .col-4-4-2-gap please?
Apparently, many people have used this notation :)

**Comment by yigitserdar** [comment]
ok. i'll pull request as it. :)
