### ISSUE TITLE
Create CSS Rows - rows height between 50px and auto

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#106]
We need a class to define those row sizes
Please write your code in this file: https://github.com/maevanapcontact/Ulight/blob/master/src/scss/styles.scss

Plase create a second class to achieve the same result but with a gap (between rows only) of 1em

**Comment by mattbudde** [comment]
Is this the kind of solution you are looking for? Not sure i understand the issue.

.row-size-50 {
  max-height: 50px;
  height: auto;
}

**Comment by maevanapcontact** [comment]
Hi!
This is the kind of result, but could you please use CSS Grid? :)
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-rows
