### ISSUE TITLE
Create design for BUTTON, A and Q elements matching BASIC template

### ISSUE THREAD

**Issue by SFromentarius** [maevanapcontact/Ulight#112]
We need to have the design for the **`<button>`, `<a>`** and **`<q>`** elements, matching the **basic template**.

The basic template: https://github.com/maevanapcontact/Ulight/blob/master/docs/images/templates/t-basic.png

You can create the files
- t-basic-button.png
- t-basic-a.png
- t-basic-q.png

and add them to a folder you will create, "t-basic-elements", in here
https://github.com/maevanapcontact/Ulight/blob/master/docs/images/templates

**Comment by MartaAG** [comment]
I can do this
