### ISSUE TITLE
Create design for TABLE and IMG elements matching BASIC template

### ISSUE THREAD

**Issue by SFromentarius** [maevanapcontact/Ulight#113]
We need to have the design for the **`<table>`** and **`<img>`** elements, matching the **basic template**.

The basic template: https://github.com/maevanapcontact/Ulight/blob/master/docs/images/templates/t-basic.png

You can create the files
- t-basic-table.png
- t-basic-img.png

and add them to the folder "t-basic-elements" in here
https://github.com/maevanapcontact/Ulight/blob/master/docs/images/templates

**Comment by MartaAG** [comment]
I can do this too
