### ISSUE TITLE
Create design for BUTTON, A and Q elements matching LIGHT template

### ISSUE THREAD

**Issue by SFromentarius** [maevanapcontact/Ulight#114]
We need to have the design for the **`<button>`, `<a>`** and **`<q>`** elements, matching the **light template**.

The light template: https://github.com/maevanapcontact/Ulight/blob/master/docs/images/templates/t-light.png

You can create the files
- t-light-button.png
- t-light-a.png
- t-light-q.png

and add them to a folder you will create, "t-light-elements", in here
https://github.com/maevanapcontact/Ulight/blob/master/docs/images/templates

**Comment by rodcunha** [comment]
I will give a go at this if I can.
