### ISSUE TITLE
Integrate the HEADER to the template BLUE

### ISSUE THREAD

**Issue by SFromentarius** [maevanapcontact/Ulight#124]
Integrate the `<header>` of the blue template.

Template: https://github.com/maevanapcontact/Ulight/blob/master/docs/images/templates/t-blue.png
 Write the SCSS code here: https://github.com/maevanapcontact/Ulight/blob/master/src/scss/themes/t-blue.scss

We need to translate the `<header>` element in SCSS inside the dedicated class.

**Comment by valnicky** [comment]
Hi, I'll try this one too. Thanks
