### ISSUE TITLE
Integrate the SECTION to the template BLUE

### ISSUE THREAD

**Issue by SFromentarius** [maevanapcontact/Ulight#125]
Integrate the `<section>` of the blue template.

Template: https://github.com/maevanapcontact/Ulight/blob/master/docs/images/templates/t-blue.png
 Write the SCSS code here: https://github.com/maevanapcontact/Ulight/blob/master/src/scss/themes/t-blue.scss

We need to translate the `<section>` element in SCSS inside the dedicated class.

**Comment by valnicky** [comment]
Hi, I'll try this one :) , tell me if something is wrong Thanks
