### ISSUE TITLE
Integrate the ARTICLE to the template BLUE

### ISSUE THREAD

**Issue by SFromentarius** [maevanapcontact/Ulight#126]
Integrate the `<article>` of the blue template.

Template: https://github.com/maevanapcontact/Ulight/blob/master/docs/images/templates/t-blue.png
 Write the SCSS code here: https://github.com/maevanapcontact/Ulight/blob/master/src/scss/themes/t-blue.scss

We need to translate the `<article>` element in SCSS inside the dedicated class.

**Comment by valnicky** [comment]
hi, I'm doing this one :) thanks
