### ISSUE TITLE
Integrate the ASIDE to the template BLUE

### ISSUE THREAD

**Issue by SFromentarius** [maevanapcontact/Ulight#127]
Integrate the `<aside>` of the blue template.

Template: https://github.com/maevanapcontact/Ulight/blob/master/docs/images/templates/t-blue.png
 Write the SCSS code here: https://github.com/maevanapcontact/Ulight/blob/master/src/scss/themes/t-blue.scss

We need to translate the `<aside>` element in SCSS inside the dedicated class.

**Comment by valnicky** [comment]
Hi, I'll do this, but how much is the margin? where could I see it? thank you
