### ISSUE TITLE
Integrate the FOOTER to the template BLUE

### ISSUE THREAD

**Issue by SFromentarius** [maevanapcontact/Ulight#128]
Integrate the `<footer>` of the blue template.

Template: https://github.com/maevanapcontact/Ulight/blob/master/docs/images/templates/t-blue.png
 Write the SCSS code here: https://github.com/maevanapcontact/Ulight/blob/master/src/scss/themes/t-blue.scss

We need to translate the `<footer>` element in SCSS inside the dedicated class.

**Comment by matijagalina** [comment]
Should I push this style to all elements of this template since there was no further discussion about it on Slack?
I can leave the opacity shape on body like on codepen or I can delete it from the final pull request?
https://codepen.io/matijagalina/pen/ypqWWL

**Comment by valnicky** [comment]
Hi, I'm doing this too. thank you
