### ISSUE TITLE
Integrate ORANGE Theme in SCSS - CSS

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#138]
Translate in SCSS - CSS the ORANGE theme available here:
https://github.com/maevanapcontact/Ulight/blob/master/docs/images/templates/t-orange.png

You can create the t-orange.scss file here:
https://github.com/maevanapcontact/Ulight/tree/master/src/scss/themes

and follow this example for the structure: https://github.com/maevanapcontact/Ulight/blob/master/src/scss/themes/t-basic.scss

**Comment by matijagalina** [comment]
Here is the code for button, links and quote:
https://codepen.io/matijagalina/pen/VQYYvQ?editors=1100

I'm not quite sure what to do regarding `td` element and about `img` tag - I can make it round with border radius but for the orange overlay the image needs to be inside the overlay container to work like pictured. With `:hover` property I can use only regular `opacity`, not the orange one.

**Comment by ferhansahin** [comment]
I have started working on it but the header and nav will take some time :) Till when I should share the completed code?
Here is the recent code; https://codepen.io/ferhansahin/pen/wyBzMO

**Comment by maevanapcontact** [comment]
Hi! Great start :) 
Okay then, the deadline is on February 1st, would it be OK for you?
