### ISSUE TITLE
Integrate the Inline elements of ORANGE theme - SCSS - CSS

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#139]
Translate in SCSS - CSS the buttons of the ORANGE theme available here:
https://github.com/maevanapcontact/Ulight/blob/master/docs/images/templates/t-orange_buttons.png

You can create the classes in the t-orange.scss available here (or create it if not existing):
https://github.com/maevanapcontact/Ulight/tree/master/src/scss/themes

**Comment by matijagalina** [comment]
Here is the code for button, links and quote:
https://codepen.io/matijagalina/pen/VQYYvQ?editors=1100

I'm not quite sure what to do regarding `td` element and about `img` tag - I can make it round with border radius but for the orange overlay the image needs to be inside the overlay container to work like pictured. With `:hover` property I can use only regular `opacity`, not the orange one.

**Comment by maevanapcontact** [comment]
Great job with your code, it is perfect for me
About the <td>, you can define the border on both <td> and <table> (and using border-collapse as well
For the image, you can put it in a container

Those things will be explained in the documentation :)
