### ISSUE TITLE
Integrate the Theme 2 in SCSS - CSS

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#140]
Translate in SCSS - CSS the THEME 2 available here:
https://github.com/maevanapcontact/Ulight/blob/master/docs/images/templates/t_2.png

You can create the t-2.scss file here:
https://github.com/maevanapcontact/Ulight/tree/master/src/scss/themes

and follow this example for the structure: https://github.com/maevanapcontact/Ulight/blob/master/src/scss/themes/t-basic.scss

**Comment by haithamsha** [comment]
Is that valid 
https://codepen.io/haithamsha/pen/ppMrNw
This is the first time for me , but guide me and I do what do you want :)

**Comment by maevanapcontact** [comment]
Hi! It is a really good start here :)
Look at the NAV, HEADER and FOOTER, on the bottom they have some extra styling.
You can also put the HEADER and ARTICLE width to something like 95% and centering them :)

**Comment by haithamsha** [comment]
Thanks I gonna fix it

**Comment by haithamsha** [comment]
Hi, I made some modification could you take a look please, 
https://codepen.io/haithamsha/pen/ppMrNw
are the left carve of the nav and article required? and what is the NAV, HEADER and FOOTER, on the bottom common styles could you explain more?, thanks.
