### ISSUE TITLE
Build the website - Multiple tasks Front-End HTML/ CSS

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#166]
We need to build the website to present the project and to allow the users to download the Framework files.
Here is the Web design: https://github.com/maevanapcontact/Ulight/tree/master/website/webdesign

As this task is big, we will work altogether at this, it is not a single-person issue.

The deadline is on Thursday, February 1st!

Here is the content of the website: https://github.com/maevanapcontact/Ulight/tree/master/website/content

And here is where we can write our code
https://github.com/maevanapcontact/Ulight/tree/master/website/src

Please propose your code on codepen first!

The fonts: 
- https://fonts.google.com/specimen/Lato
- https://fonts.google.com/specimen/Capriola

The icons:
- https://orioniconlibrary.com/all-icons

**Comment by SFromentarius** [comment]
Hi! What do you think of this one for the buttons/links?
Also, what is the font used? Instead of "a:active" I made a "a:hover" just for you to see :) 

https://codepen.io/SarahF3000/pen/aqbVxJ

**Comment by SFromentarius** [comment]
I am working on the header :)

**Comment by maevanapcontact** [comment]
Thanks @SFromentarius for asking about the fonts, I have added them in the description!
Also, the buttons/ links sound great!

**Comment by eaczechova** [comment]
Hi! So I will try to do the footer :)

**Comment by haithamsha** [comment]
I'm working on about view, :)

**Comment by matijagalina** [comment]
I have made basic index.html file for it. What do you think guys? Where is written "font awesome" I plan to include `i` element with font awesome classes

https://codepen.io/matijagalina/pen/paopYP?editors=1010#

**Comment by haithamsha** [comment]
@matijagalina  good job, yes ```i``` element is suitable with font awesome.

**Comment by matijagalina** [comment]
Great, I will brush it up more - add font awesome and complete some links href before making pull request
If anybody else has something to add after that - to quote Shia LaBeouf - Just Do it!

**Comment by SFromentarius** [comment]
What do you think of this for the header? 
https://codepen.io/SarahF3000/pen/GQROzB

For the links/buttons I understood the border is only on hover and I also add the `:active` style (that we can see just by stay click on it :) ).  Tell me if not :)

**Comment by haithamsha** [comment]
Good job, I suggest to make the cursor be pointer in hovers, and also instead of using font-awesome classes in CSS we can make class (icon) and pass it to all and change it only in CSS e.g.
```<i class="fab fa-github icon"></i>```
```i class="fab fa-facebook icon">```
and in CSS
```.icon{

}
.icon:hover{
  
}```

**Comment by haithamsha** [comment]
@matijagalina Waiting for index.html page to work on it I'm working in a demo page now. :)

**Comment by matijagalina** [comment]
I have made pull request with only font awesome classes, but if we agree about icon class there will be no problem in updating the html file ;)

**Comment by eaczechova** [comment]
What do you think about thia as footer?

https://codepen.io/eaczechova/pen/YezYNO?editors=1100

**Comment by matijagalina** [comment]
@eaczechova Try to make icons bigger and add some margin between them so they can be divided evenly bellow documentation link and with that in the center of the footer like [here](https://github.com/maevanapcontact/Ulight/blob/master/website/webdesign/Home.jpg)

**Comment by eaczechova** [comment]
@matijagalina I have made the icons a bit bigger and add some extra right/left padding, what do you think?

https://codepen.io/eaczechova/pen/YezYNO?editors=1100

**Comment by matijagalina** [comment]
@eaczechova Excellent :)

**Comment by matijagalina** [comment]
Here are also about.html and documentation.html pages for you to review:
https://codepen.io/matijagalina/pen/JpjZoe?editors=1000#
https://codepen.io/matijagalina/pen/rJNKdQ?editors=1000

**Comment by haithamsha** [comment]
About view
https://codepen.io/haithamsha/pen/JpjZxP
I'm going work on responsive, but give me your feedback.
- I'm bad with responsive images, how can I fix the logo image.
- Please tell me what is the icons in history and team sections, because I use similar icons but not in the design.
- idea-history-team under "About Ulight" could you tell me what is the hex decimal color of it?.

**Comment by matijagalina** [comment]
For logo - just change `height` to `auto`  (responsive images are made in most cases with width 100% and height auto ; here we can make width with exact size using px, but height must be auto)
Yeah, I also had that dilema - you can see in my about.html proposal - I have left blank img tag because there isn't icons like that in font awesome so we can decide about that later
I'm not sure about the hex of color - the designer will have to tell that to us

**Comment by haithamsha** [comment]
Yes, the image has fixed, can I change your HTML code and use mine if is that stranded?

**Comment by MartaAG** [comment]
Hello everyone! If you have question about design matter etc don't hesitate and ask me :) you can PM me or find me on slack, whatever you like :) 
Font used for body is Lato, Capriola for headings, and I didn't tell you earlier, my bad, I used orions icons (https://orioniconlibrary.com/) which is completely free.
But if you like font awesome and the design looks goods, that also fine :)

**Comment by matijagalina** [comment]
@haithamsha I propose to wait when we push the basic html files on github - which I added here in comments and then we can add to them or replace as we go ;)

**Comment by haithamsha** [comment]
Hi Marta, could you please tell me what is the color of the font for about page (this part "Idea - History - Team").

**Comment by haithamsha** [comment]
@matijagalina  Good idea :)

**Comment by MartaAG** [comment]
I generally used three colors:
#00b8d4 -> blue
[9:41 PM]
#fa990e -> orange
[9:42 PM]
#cfd8dc -> gray

**Comment by MartaAG** [comment]
OK, I will leave you more information:

For header (home, about, documentation) I used Capriola, not Lato :) Lato is used only for bodytext (regular) on home text ("...A light framework..."), weight: thin

Also capriola is used for download section (sign: "download), lato is used for "download minify version/full version). 

If anything is not clear, just write :) anyway, great job!

**Comment by maevanapcontact** [comment]
It is done :) Thanks for your quick and great work!

**Comment by haithamsha** [comment]
Hi guys, @matijagalina I have done, is that ok if I update your code (about view part)?

**Comment by haithamsha** [comment]
I have made a pull request , added about code in about.html page that @matijagalina  have done, and references this files in about.html page
```
<!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Capriola" rel="stylesheet">
    <!-- font awesome cdn -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- custom css -->
    <link rel="stylesheet" href="../src/assets/css/style.css">
```

**Comment by matijagalina** [comment]
I have taken documentation view, but I will leave header and footer to @SFromentarius  and @eaczechova because yours header and footer will be the same on all three views. How's that going?

**Comment by matijagalina** [comment]
Okay, so this is what I have for now:
https://codepen.io/matijagalina/full/rJaJgQ/
Instead of icons I have put placeholders or blue background where the infographic should go.
I didn't add media queries so it isn't responsive. If anyone wants to help, please do. I have some commitments for the rest of this week so I won't be able to work a lot on the website, but I will try to find the time

**Comment by haithamsha** [comment]
https://codepen.io/haithamsha/pen/JpjZxP
