### ISSUE TITLE
Add Normalize.css

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#29]
We need to add the file Normalize.css on the src/assets/css

**Comment by Puritanic** [comment]
On it. What do you think about using the 7-1 pattern for CSS/SCSS files folder structure? I don't think that normalize.css file should live in the assets folder.

**Comment by maevanapcontact** [comment]
Maybe we can upgrade the structure according to our current need to don't make the things to difficult for beginners?

**Comment by Puritanic** [comment]
Sure, we don't need all that folders from the 7-1 pattern, but I still don't think that normalize.css in assets folder would make any sense :| 
On the other side, something like src/css/vendors/ folder would be more intuitive imho.

**Comment by maevanapcontact** [comment]
okay, I let you apply those changes then :)
Let's see how it looks (but we should try to use just the minimum needed)

Be sure to update the full repository as it has changed a lot :)

**Comment by RA9** [comment]
Why add normalize.css when you can do the same thing from start and you guys don't forget that this is a framework and should treat it as one and get hands on code to learn new experiences

**Comment by maevanapcontact** [comment]
Because it helps for being consistent on all the screens and devices. For now, as we are beginners, it should be really helpful to don't have bad results. There is no need to redo some existing stuff if there is no plus to do it. And it helps to start :)
