### ISSUE TITLE
Create basic template file

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#30]
We need a first basic template in HTML to test the classes of the Framework. A kind of template with a basic structure to test the classes

**Comment by kryaksy** [comment]
including test driven scripts?

**Comment by maevanapcontact** [comment]
we haven't implemented the tests yet, and the basic HTML template was already done :)
we need to define how we will do those tests before implementing them :) There is another issue open to discuss about this point

**Comment by kryaksy** [comment]
Yes I know that one. So how we test classes in this issue? Which test method are we talking about :) I think I am missing something.
