### ISSUE TITLE
Find a way to do some tests

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#32]
We need to run some tests to check if the Framework works on all the devices and browsers.
We need to find some tools to automate the tests and help us in this task.

Any idea?

**Comment by kryaksy** [comment]
Is it same thing with test automation framework? Like:
http://robotframework.org/

**Comment by maevanapcontact** [comment]
Yeah exactly! Thank you for the link. We need to make some BDD and TDD testes
We also have this one 
https://jasmine.github.io/
