### ISSUE TITLE
First set of designed nav elements

### ISSUE THREAD

**Issue by SFromentarius** [maevanapcontact/Ulight#35]
We need a DESIGN of a nav element to have a template which should be implemented later by the coders.
- This is just the DESIGN, not the code
- This is the design of the BLOCK, not inside elements
- Imagine you need to make a nav on your future website, how the block will look like? The borders, the shadows, the background?

**Comment by RA9** [comment]
If I may ask for  instance only the standard with a code like this one :
nav {
border: ;
}

**Comment by SFromentarius** [comment]
For now, we need ideas of **design** for nav elements, it's not about the code yet :) 
If you have some, you can directly drag & drop the image file into here.

**Comment by itskirstyann** [comment]
Can I just say - if the design was to implement just the content and doesn't have a background (transparent and just text) are we to just use placeholders like <text> as an example?

**Comment by maevanapcontact** [comment]
The design is mainly the block design, no the content. Imagine the user want to add a class inside the <header> tag to have the border, background, box-shadow and so on
