### ISSUE TITLE
Integrate the NAV of template BASIC

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#46]
Integrate the `<nav>` of the basic template

Template: https://github.com/maevanapcontact/Ulight/blob/ulight-dev/docs/images/templates/t-basic.png
Write the SCSS code here: https://github.com/maevanapcontact/Ulight/blob/ulight-dev/src/scss/themes/t-basic.scss

We need to translate the `<nav>` element in SCSS inside the dedicated class

**Comment by Thomas1981Lang** [comment]
Hi! I like to help, but I have no experience with SCSS. Can I write it in CSS and than convert it to SCSS?

**Comment by maevanapcontact** [comment]
you can write pure CSS in the SCSS file.
SCSS just give you more tools to work with CSS but you don't HAVE to use them :)
Feel free to code as you prefer, but only in the file linked
