### ISSUE TITLE
Integrate the HEADER of template BASIC

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#47]
Integrate the `<header>` of the basic template

Template: https://github.com/maevanapcontact/Ulight/blob/ulight-dev/docs/images/templates/t-basic.png
Write the SCSS code here: https://github.com/maevanapcontact/Ulight/blob/ulight-dev/src/scss/themes/t-basic.scss

We need to translate the `<header>` element in SCSS inside the dedicated class

**Comment by matijagalina** [comment]
Added a solution on the issue nr. 51
