### ISSUE TITLE
Integrate the SECTION of template BASIC

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#48]
Integrate the `<section>` of the basic template

Template: https://github.com/maevanapcontact/Ulight/blob/ulight-dev/docs/images/templates/t-basic.png
Write the SCSS code here: https://github.com/maevanapcontact/Ulight/blob/ulight-dev/src/scss/themes/t-basic.scss

We need to translate the `<section>` element in SCSS inside the dedicated class

**Comment by valnicky** [comment]
I'll try to do this. If it is not ok, tell me please and I'll change it.
