### ISSUE TITLE
Integrate the ARTICLE of the template BASIC

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#49]
Integrate the `<article>` of the basic template

Template: https://github.com/maevanapcontact/Ulight/blob/ulight-dev/docs/images/templates/t-basic.png
Write the SCSS code here: https://github.com/maevanapcontact/Ulight/blob/ulight-dev/src/scss/themes/t-basic.scss

We need to translate the `<article>` element in SCSS inside the dedicated class

**Comment by RA9** [comment]
I will handle it but only the tag without dummies
