### ISSUE TITLE
Integrate the ASIDE of the template BASIC

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#50]
Integrate the `<aside>` of the basic template

Template: https://github.com/maevanapcontact/Ulight/blob/ulight-dev/docs/images/templates/t-basic.png
Write the SCSS code here: https://github.com/maevanapcontact/Ulight/blob/ulight-dev/src/scss/themes/t-basic.scss

We need to translate the `<aside>` element in SCSS inside the dedicated class

**Comment by matijagalina** [comment]
Added a solution on the issue nr. 51
