### ISSUE TITLE
Integrate the FOOTER of the template BASIC

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#51]
Integrate the `<footer>` of the basic template

Template: https://github.com/maevanapcontact/Ulight/blob/ulight-dev/docs/images/templates/t-basic.png
Write the SCSS code here: https://github.com/maevanapcontact/Ulight/blob/ulight-dev/src/scss/themes/t-basic.scss

We need to translate the `<footer>` element in SCSS inside the dedicated class

**Comment by matijagalina** [comment]
Here is my solution: 
https://codepen.io/matijagalina/pen/ZvvjgE?editors=1100#

There is also header and aside included - will comment on that issues also

**Comment by maevanapcontact** [comment]
approved for me :)
Thanks for all your work!
