### ISSUE TITLE
Integrate the NAV of the template LIGHT

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#52]
Integrate the `<nav>` of the light template

Template: https://github.com/maevanapcontact/Ulight/blob/ulight-dev/docs/images/templates/t-light.png
Write the SCSS code here: https://github.com/maevanapcontact/Ulight/blob/ulight-dev/src/scss/themes/t-light.scss

We need to translate the `<nav>` element in SCSS inside the dedicated class

**Comment by matijagalina** [comment]
I had something like that on my mind:
https://codepen.io/matijagalina/pen/rpwZOd
I don't know if it's to much - maybe it needs to be simple in the start. I have chosen flexbox because it's well supported by now (97.72% on caniuse.com)

**Comment by maevanapcontact** [comment]
Thanks for your proposal, it looks great :) and your code is really clean
We use CSS Grid for this project, that's the main difference with Bootstrap, is it possible to use it instead?
Also, the colors are important here, I see that you have used a different background color, any reason for that?

**Comment by matijagalina** [comment]
Sure, I can use grid. Actually, I prefer grid, I just didn't know that we will gonna use it :)
I didn't know about the colors also, I assumed it was just for the illustration. It would be useful to add somewhere the hsl code of the color for better reproduction, but I can always use some third party color picker tool to extract if from template.
Here is the updated code with grid and color from the template (#474747):
https://codepen.io/matijagalina/pen/rpwZOd

**Comment by maevanapcontact** [comment]
You have done a great job here!
Thanks for everything you have done, it looks perfect like that :)

You can write as it is in the JS panel in the SCSS folder but should you use the classes name you have used in the CSS file?

Thank you :)

**Comment by matijagalina** [comment]
Yes, the code inside JS panel was there just to show nesting part, I have put it now inside the CSS panel in that form and will be doing pull request today 
https://codepen.io/matijagalina/full/rpwZOd/
