### ISSUE TITLE
Integrate the HEADER of the template LIGHT

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#53]
Integrate the `<header>` of the light template

Template: https://github.com/maevanapcontact/Ulight/blob/ulight-dev/docs/images/templates/t-light.png
Write the SCSS code here: https://github.com/maevanapcontact/Ulight/blob/ulight-dev/src/scss/themes/t-light.scss

We need to translate the `<header>` element in SCSS inside the dedicated class

**Comment by matijagalina** [comment]
Hi! This is my proposal for initial styling of t-light-header and also for other elements in this template (section, article, aside, footer) for which I can make individual commits.
https://codepen.io/matijagalina/pen/opeLdd

**Comment by maevanapcontact** [comment]
great job :) Thanks for your contribution
Yes, please, make separate commit (one per block (class))
I will close the issues when you will be done :)
