### ISSUE TITLE
Implementing Grid of 12 columns using CSS Grid

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#73]
We need to have a single class in a container to let the user have a grid of 12 columns.
It was previously done but we need to implement it using the CSS Grid

You can write your code at the very bottom of this file 
https://github.com/maevanapcontact/Ulight/blob/ulight-dev/src/scss/styles.scss

**Comment by matijagalina** [comment]
Like this?
https://codepen.io/matijagalina/pen/goXOZB

**Comment by maevanapcontact** [comment]
As usually, your solution is great :)
That's OK for me!

**Comment by matijagalina** [comment]
Will submit then, thanks :)
