### ISSUE TITLE
Create web design 1 TEMPLATE BLOCKS

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#77]
**Create a template for the web design 1 which will be implemented in CSS in the Framework**
- NAV element
- HEADER element
- ASIDE element
- ARTICLE element
- ASIDE element
- FOOTER element
- DIV element

You can follow those templates:
https://github.com/maevanapcontact/Ulight/tree/master/docs/images/templates

DON'T FORGET TO ADD THE `<div>` element!

When it is done, please add your .JPG file in the same folder!

**Comment by dalnoki** [comment]
Can I take this one?:)

**Comment by maevanapcontact** [comment]
Of course! :)
Please comment here when you are done before making your pull request :)
