### ISSUE TITLE
Create Web Design 2 TEMPLATE BLOCK

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#78]
**Create a template for the web design 2 which will be implemented in CSS in the Framework**
- NAV element
- HEADER element
- ASIDE element
- ARTICLE element
- ASIDE element
- FOOTER element
- DIV element

You can follow those templates:
https://github.com/maevanapcontact/Ulight/tree/master/docs/images/templates

DON'T FORGET TO ADD THE `<div>` element!

When it is done, please add your .JPG file in the same folder!

**Comment by KatMi** [comment]
Can I take a shot on this one?
