### ISSUE TITLE
Add 1 direction CSS Grid from 1 columns to 16 columns

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#79]
We need to implement some CSS Grids
- 1 column
- 2 columns
- 3 columns
- 4 columns
- 5 columns
- 6 columns
- 7 columns
- 8 columns
- 9 columns
- 10 columns
- 11 columns
- 13 columns
- 14 columns
- 15 columns
- 16 columns

You can take example of the 12 columns which was already done here:
https://github.com/maevanapcontact/Ulight/blob/master/src/scss/styles.scss

Please use one class per Grid (one class for 1 column Grid, one class for 2 columns Grid and so on)

Write those classes in the same file as the current 12 columns Grid

**Please use CSS Grid and fr unit**

**Comment by matijagalina** [comment]
I have expanded my codepen file where I have wrote class for a grid of 12 columns with other classes covering the grid from 1 to 16 columns
https://codepen.io/matijagalina/pen/goXOZB?editors=0100

Will do the same for rows so I'm gonna leave my comment on that issue also

**Comment by maevanapcontact** [comment]
Great job! Thanks :) 
You can make the pull request
