### ISSUE TITLE
Add 1 Direction CSS Grid from 1 row to 16 rows

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#80]
Following the example of the columns, we need 16 classes to manage the rows.

We need to implement some CSS Grids
- 1 row
- 2 rows
- 3 rows
- 4 rows
- 5 rows
- 6 rows
- 7 rows
- 8 rows
- 9 rows
- 10 rows
- 11 rows
- 12 rows
- 13 rows
- 14 rows
- 15 rows
- 16 rows

You can take example of the 12 columns which was already done here:
https://github.com/maevanapcontact/Ulight/blob/master/src/scss/styles.scss

Please use one class per Grid (one class for 1-row Grid, one class for 2-rows Grid and so on)

Write those classes in the same file as the current 12 columns Grid

**Please use CSS Grid and fr unit**
  
Here are the names of the classes to use:
```
.row-1 { ... }
.row-2 { ... }
.row-3 { ... }
...
```

**Comment by matijagalina** [comment]
My solution: 
https://codepen.io/matijagalina/pen/vppJpz?editors=1100

**Comment by maevanapcontact** [comment]
Perfect as well
OK for the pull request :)
