### ISSUE TITLE
Create 1 template HTML to test the Framework

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#81]
We need a single HTML page with those following elements:
- HEADER
- NAV
- ASIDE
- ARTICLE
- SECTION
- DIV
- FOOTER

We will also need some nested `<div>` to apply the CSS Grid on them

e.g
```
<div>
    <div></div>
    <div></div>
    <div>
        <div></div>
    </div>
</div>
```

but with content inside of course!

Please add your file there:
https://github.com/maevanapcontact/Ulight/tree/master/src

You can use a name like template-1.html

Here is an example of what you can do:
https://github.com/maevanapcontact/Ulight/blob/master/src/index.html

Feel free to do anything you like :)

**Comment by yigitserdar** [comment]
hi. i want to try this.

**Comment by maevanapcontact** [comment]
Great :)
This task is for you then

**Comment by yigitserdar** [comment]
what do you say about this: [codepen](https://codepen.io/yigitserdar/pen/vppVoN)

**Comment by maevanapcontact** [comment]
That works for me! You have added some nested `<div>` so that's great :)
