### ISSUE TITLE
Create template 2 HTML to test the Framework

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#82]
We need a single HTML page with those following elements:
- HEADER
- NAV
- ASIDE
- ARTICLE
- SECTION
- DIV
- FOOTER

We will also need some nested `<div>` to apply the CSS Grid on them

e.g
```
<div>
    <div></div>
    <div></div>
    <div>
        <div></div>
    </div>
</div>
```

but with content inside of course!

Please add your file there:
https://github.com/maevanapcontact/Ulight/tree/master/src

You can use a name like template-2.html

Here is an example of what you can do:
https://github.com/maevanapcontact/Ulight/blob/master/src/index.html

Feel free to do anything you like :)

**Comment by RA9** [comment]
Well I will handle it , hope to make it responsive using the framework

**Comment by maevanapcontact** [comment]
You don't have to write CSS here, only HTML :)

**Comment by RA9** [comment]
Yeah I know just wanted to use the Framework selectors to make the HTML more responsive
I will soon finished , Was doing a little task on my team project called Quizzilla
