### ISSUE TITLE
Create Template 3 HTML to test the Framework

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight#83]
We need a single HTML page with those following elements:
- HEADER
- NAV
- ASIDE
- ARTICLE
- SECTION
- DIV
- FOOTER

We will also need some nested `<div>` to apply the CSS Grid on them

e.g
```
<div>
    <div></div>
    <div></div>
    <div>
        <div></div>
    </div>
</div>
```

but with content inside of course!

Please add your file there:
https://github.com/maevanapcontact/Ulight/tree/master/src

You can use a name like template-3.html

Here is an example of what you can do:
https://github.com/maevanapcontact/Ulight/blob/master/src/index.html

Feel free to do anything you like :)

**Comment by moaaz-bhnas** [comment]
I'm on it :+1:

**Comment by maevanapcontact** [comment]
Great :)
