### ISSUE TITLE
Integrate the NAV to the template NEWS

### ISSUE THREAD

**Issue by SFromentarius** [maevanapcontact/Ulight#90]
Integrate the `<nav>` of the news template.

Template: https://github.com/maevanapcontact/Ulight/blob/master/docs/images/templates/t-news.jpg
 Write the SCSS code here: https://github.com/maevanapcontact/Ulight/blob/master/src/scss/themes/t-news.scss

We need to translate the `<nav>` element in SCSS inside the dedicated class.

**Comment by vilanelle** [comment]
I'd like to do this one, please :)
