### ISSUE TITLE
Integrate the ASIDE to the template NEWS

### ISSUE THREAD

**Issue by SFromentarius** [maevanapcontact/Ulight#94]
Integrate the `<aside>` of the news template.

Template: https://github.com/maevanapcontact/Ulight/blob/master/docs/images/templates/t-news.jpg
 Write the SCSS code here: https://github.com/maevanapcontact/Ulight/blob/master/src/scss/themes/t-news.scss

We need to translate the `<aside>` element in SCSS inside the dedicated class.

**Comment by matijagalina** [comment]
I'll do it ;)

**Comment by matijagalina** [comment]
My solution: 
https://codepen.io/matijagalina/pen/ppaKwR
